import {
  OPENAPI_DOCUMENT_PATH,
  OPENAPI_JSON_PATH,
} from "../../src/platform/http/openapi";
import { ApiIntegrationTestHarness } from "./api-test-harness";

interface OpenApiSchema {
  readonly type?: string;
  readonly format?: string;
  readonly enum?: readonly string[];
  readonly nullable?: boolean;
  readonly items?: OpenApiSchema;
  readonly $ref?: string;
  readonly required?: readonly string[];
  readonly properties?: Readonly<Record<string, OpenApiSchema>>;
}

interface OpenApiOperation {
  readonly tags?: readonly string[];
  readonly summary?: string;
  readonly security?: readonly Readonly<Record<string, readonly string[]>>[];
  readonly parameters?: readonly {
    readonly name: string;
    readonly in: string;
    readonly required?: boolean;
  }[];
  readonly requestBody?: {
    readonly content: Readonly<Record<string, { readonly schema: OpenApiSchema }>>;
  };
  readonly responses: Readonly<
    Record<
      string,
      {
        readonly description?: string;
        readonly content?: Readonly<
          Record<string, { readonly schema: OpenApiSchema }>
        >;
      }
    >
  >;
}

interface OpenApiDocument {
  readonly openapi: string;
  readonly info: { readonly title: string; readonly version: string };
  readonly paths: Readonly<
    Record<string, Readonly<Record<string, OpenApiOperation>>>
  >;
  readonly components: {
    readonly schemas: Readonly<Record<string, OpenApiSchema>>;
    readonly securitySchemes: Readonly<Record<string, { readonly type: string }>>;
  };
}

/**
 * NFR-009. The document is generated by `SwaggerModule` from the same controller metadata
 * and DTO classes the `ValidationPipe` validates against, so this suite asserts that the
 * generated contract actually contains the procurement surface — a Markdown file could
 * claim as much while the application did something else.
 *
 * No database is needed: nothing here executes a route.
 */
describe("generated OpenAPI document", () => {
  let api: ApiIntegrationTestHarness;
  let document: OpenApiDocument;

  beforeAll(async () => {
    api = await ApiIntegrationTestHarness.start();

    const response = await api.get(`/${OPENAPI_JSON_PATH}`);
    expect(response.status).toBe(200);
    document = response.body as OpenApiDocument;
  }, 120_000);

  afterAll(async () => {
    if (api !== undefined) {
      await api.stop();
    }
  });

  function operation(path: string, method: string): OpenApiOperation {
    const found = document.paths[path]?.[method];

    if (found === undefined) {
      throw new Error(`${method.toUpperCase()} ${path} is missing from the document`);
    }

    return found;
  }

  function schema(name: string): OpenApiSchema {
    const found = document.components.schemas[name];

    if (found === undefined) {
      throw new Error(`schema ${name} is missing from the document`);
    }

    return found;
  }

  it("is served as JSON and as a browsable page", async () => {
    expect(document.openapi.startsWith("3.")).toBe(true);
    expect(document.info.title).toBe("VendorFlow API");

    const page = await api.get(`/${OPENAPI_DOCUMENT_PATH}`);
    expect(page.status).toBe(200);
  });

  it("exposes every purchase request path and method", () => {
    // Quotation nests its routes under the request they belong to, because a quote has no life
    // outside one. They are a different module's controller sharing a prefix, which is exactly
    // why this assertion enumerates the whole prefix rather than one controller's routes.
    expect(
      Object.entries(document.paths)
        .filter(([path]) => path.startsWith("/purchase-requests"))
        .flatMap(([path, methods]) =>
          Object.keys(methods).map((method) => `${method.toUpperCase()} ${path}`),
        )
        .sort(),
    ).toEqual([
      "DELETE /purchase-requests/{purchaseRequestId}",
      "GET /purchase-requests",
      "GET /purchase-requests/awaiting-my-approval",
      "GET /purchase-requests/awaiting-quotation",
      "GET /purchase-requests/{purchaseRequestId}",
      "GET /purchase-requests/{purchaseRequestId}/quotes",
      "POST /purchase-requests",
      "POST /purchase-requests/{purchaseRequestId}/approval-decision",
      "POST /purchase-requests/{purchaseRequestId}/cancel",
      "POST /purchase-requests/{purchaseRequestId}/quotes",
      "POST /purchase-requests/{purchaseRequestId}/quotes/{supplierQuoteId}/select",
      "POST /purchase-requests/{purchaseRequestId}/quotes/{supplierQuoteId}/withdraw",
      "POST /purchase-requests/{purchaseRequestId}/submit",
      "PUT /purchase-requests/{purchaseRequestId}",
    ]);
  });

  it("documents the request body from the DTO the ValidationPipe uses", () => {
    const create = operation("/purchase-requests", "post");

    expect(create.tags).toContain("purchase-requests");
    expect(
      create.requestBody?.content["application/json"]?.schema.$ref,
    ).toBe("#/components/schemas/PurchaseRequestDraftDto");

    const draft = schema("PurchaseRequestDraftDto");
    expect(Object.keys(draft.properties ?? {}).sort()).toEqual([
      "items",
      "justification",
      "neededBy",
    ]);
    expect(draft.required).toEqual(
      expect.arrayContaining(["justification", "neededBy", "items"]),
    );
    expect(draft.properties?.items?.items?.$ref).toBe(
      "#/components/schemas/PurchaseRequestItemDto",
    );

    const item = schema("PurchaseRequestItemDto");
    expect(Object.keys(item.properties ?? {}).sort()).toEqual([
      "description",
      "estimatedUnitPriceCents",
      "quantity",
      "unitOfMeasure",
    ]);
    // The wire types the domain actually accepts: exact decimal text, never JSON numbers.
    expect(item.properties?.quantity?.type).toBe("string");
    expect(item.properties?.estimatedUnitPriceCents?.type).toBe("string");
    // Server-owned fields are absent from the contract, exactly as they are absent from the
    // DTO the pipe whitelists against.
    for (const forbidden of [
      "organizationId",
      "requesterId",
      "departmentId",
      "status",
      "estimatedTotalCents",
      "position",
      "roles",
    ]) {
      expect(Object.keys(draft.properties ?? {})).not.toContain(forbidden);
      expect(Object.keys(item.properties ?? {})).not.toContain(forbidden);
    }
  });

  it("documents the response schemas, including the item lines", () => {
    const read = operation("/purchase-requests/{purchaseRequestId}", "get");

    expect(read.responses["200"]?.content?.["application/json"]?.schema.$ref).toBe(
      "#/components/schemas/PurchaseRequestResponse",
    );

    const response = schema("PurchaseRequestResponse");
    expect(Object.keys(response.properties ?? {}).sort()).toEqual([
      "approval",
      "cancelledAt",
      "createdAt",
      "departmentId",
      "estimatedTotalCents",
      "id",
      "items",
      "justification",
      "neededBy",
      // FR-026, added in this phase. Both are null until the corresponding thing exists, so an
      // existing client that ignores them is unaffected.
      "purchaseOrder",
      "requesterId",
      "selectedQuote",
      "status",
      "submittedAt",
      "updatedAt",
    ]);
    expect(response.properties?.estimatedTotalCents?.type).toBe("string");
    expect(response.properties?.status?.enum).toEqual([
      "DRAFT",
      "SUBMITTED",
      "IN_QUOTATION",
      "IN_FINAL_APPROVAL",
      "APPROVED",
      "ORDERED",
      "REJECTED",
      "CANCELLED",
    ]);
    expect(response.properties?.items?.items?.$ref).toBe(
      "#/components/schemas/PurchaseRequestItemResponse",
    );

    const item = schema("PurchaseRequestItemResponse");
    expect(item.properties?.quantity?.type).toBe("string");
    expect(item.properties?.estimatedLineTotalCents?.type).toBe("string");

    const page = schema("PurchaseRequestPageResponse");
    expect(page.properties?.items?.items?.$ref).toBe(
      "#/components/schemas/PurchaseRequestSummaryResponse",
    );
    expect(page.properties?.nextCursor?.nullable).toBe(true);
  });

  it("documents the approval flow and step schemas the requester can read (FR-026)", () => {
    const response = schema("PurchaseRequestResponse");
    expect(response.properties?.approval?.nullable).toBe(true);

    const flow = schema("ApprovalFlowResponse");
    expect(Object.keys(flow.properties ?? {}).sort()).toEqual([
      "id",
      "pendingStep",
      "state",
      "steps",
    ]);
    expect(flow.properties?.state?.enum).toEqual([
      "ACTIVE",
      "COMPLETED",
      "REJECTED",
      "VOIDED",
    ]);
    expect(flow.properties?.pendingStep?.nullable).toBe(true);
    expect(flow.properties?.steps?.items?.$ref).toBe(
      "#/components/schemas/ApprovalStepResponse",
    );

    const step = schema("ApprovalStepResponse");
    expect(Object.keys(step.properties ?? {}).sort()).toEqual([
      "decidedAt",
      "decidedById",
      "decisionReason",
      "evaluatedAmountCents",
      "id",
      "role",
      "sequence",
      "state",
    ]);
    // FR-036's amount is a string for the same reason every other amount is.
    expect(step.properties?.evaluatedAmountCents?.type).toBe("string");
    expect(step.properties?.role?.enum).toEqual([
      "MANAGER",
      "PURCHASING",
      "FINANCE",
    ]);
    expect(step.properties?.state?.enum).toEqual([
      "PENDING",
      "ACTIONABLE",
      "APPROVED",
      "REJECTED",
      "VOIDED",
    ]);
  });

  it("documents the decision command as a closed world of two fields", () => {
    const decide = operation(
      "/purchase-requests/{purchaseRequestId}/approval-decision",
      "post",
    );

    expect(decide.requestBody?.content["application/json"]?.schema.$ref).toBe(
      "#/components/schemas/ApprovalDecisionDto",
    );

    const body = schema("ApprovalDecisionDto");
    expect(Object.keys(body.properties ?? {}).sort()).toEqual([
      "decision",
      "reason",
    ]);
    expect(body.required).toEqual(["decision"]);
    expect(body.properties?.decision?.enum).toEqual(["APPROVED", "REJECTED"]);

    // Nothing the server owns is expressible: not the step, not the actor, not the amount,
    // not the resulting status (MT-003, AUTHZ-005).
    for (const forbidden of [
      "approvalStepId",
      "organizationId",
      "decidedById",
      "status",
      "evaluatedAmountCents",
      "sequence",
      "role",
      "roles",
    ]) {
      expect(Object.keys(body.properties ?? {})).not.toContain(forbidden);
    }
  });

  it("documents the manager queue and its keyset page", () => {
    const queue = operation("/purchase-requests/awaiting-my-approval", "get");

    expect(
      queue.responses["200"]?.content?.["application/json"]?.schema.$ref,
    ).toBe("#/components/schemas/PurchaseRequestApprovalQueueResponse");
    expect(
      (queue.parameters ?? [])
        .filter((parameter) => parameter.in === "query")
        .map((parameter) => parameter.name)
        .sort(),
    ).toEqual(["cursor", "limit"]);

    const page = schema("PurchaseRequestApprovalQueueResponse");
    expect(page.properties?.items?.items?.$ref).toBe(
      "#/components/schemas/PurchaseRequestApprovalQueueItemResponse",
    );
    expect(page.properties?.nextCursor?.nullable).toBe(true);

    const item = schema("PurchaseRequestApprovalQueueItemResponse");
    expect(item.properties?.request?.$ref).toBe(
      "#/components/schemas/PurchaseRequestSummaryResponse",
    );
    expect(item.properties?.pendingStep?.$ref).toBe(
      "#/components/schemas/ApprovalStepResponse",
    );
  });

  it("documents the quote comparison as a bounded keyset page (FR-043, NFR-004)", () => {
    const comparison = operation(
      "/purchase-requests/{purchaseRequestId}/quotes",
      "get",
    );

    expect(
      comparison.responses["200"]?.content?.["application/json"]?.schema.$ref,
    ).toBe("#/components/schemas/SupplierQuoteListResponse");
    expect(
      (comparison.parameters ?? [])
        .filter((parameter) => parameter.in === "query")
        .map((parameter) => parameter.name)
        .sort(),
    ).toEqual(["cursor", "limit"]);
    expect(
      (comparison.parameters ?? [])
        .filter((parameter) => parameter.in === "query")
        .every((parameter) => parameter.required !== true),
    ).toBe(true);
    // A malformed cursor and an out-of-range page size are stated outcomes of this route.
    expect(Object.keys(comparison.responses).sort()).toEqual([
      "200",
      "400",
      "401",
      "403",
      "404",
    ]);

    const page = schema("SupplierQuoteListResponse");
    expect(page.properties?.items?.items?.$ref).toBe(
      "#/components/schemas/SupplierQuoteResponse",
    );
    expect(page.properties?.nextCursor?.nullable).toBe(true);
  });

  it("documents the paginated list parameters", () => {
    const list = operation("/purchase-requests", "get");
    const parameters = (list.parameters ?? []).filter(
      (parameter) => parameter.in === "query",
    );

    expect(parameters.map((parameter) => parameter.name).sort()).toEqual([
      "cursor",
      "limit",
    ]);
    expect(parameters.every((parameter) => parameter.required !== true)).toBe(
      true,
    );
  });

  it("documents the failure outcomes each operation can actually produce", () => {
    expect(
      Object.keys(operation("/purchase-requests", "post").responses).sort(),
    ).toEqual(["201", "400", "401", "403", "422"]);

    expect(
      Object.keys(
        operation("/purchase-requests/{purchaseRequestId}", "put").responses,
      ).sort(),
    ).toEqual(["200", "400", "401", "404", "409", "422"]);

    expect(
      Object.keys(
        operation("/purchase-requests/{purchaseRequestId}/submit", "post")
          .responses,
      ).sort(),
      // 400 joins the list in this phase: REL-004 requires an Idempotency-Key here, and a
      // missing or malformed one is a controlled bad request.
    ).toEqual(["200", "400", "401", "404", "409"]);

    expect(
      Object.keys(
        operation("/purchase-requests/{purchaseRequestId}", "delete").responses,
      ).sort(),
    ).toEqual(["204", "401", "404", "409"]);

    // Every controlled outcome the decision command can actually produce, including the two
    // that are security-relevant: 403 for a capability or self-approval denial, 404 for
    // anything outside the caller's department or tenant.
    expect(
      Object.keys(
        operation(
          "/purchase-requests/{purchaseRequestId}/approval-decision",
          "post",
        ).responses,
      ).sort(),
    ).toEqual(["200", "400", "401", "403", "404", "409", "422", "429"]);

    expect(
      Object.keys(
        operation("/purchase-requests/awaiting-my-approval", "get").responses,
      ).sort(),
    ).toEqual(["200", "400", "401", "403", "404", "429"]);
  });

  it("explains the security-relevant behaviour of the decision command", () => {
    const decide = operation(
      "/purchase-requests/{purchaseRequestId}/approval-decision",
      "post",
    );

    // NFR-009: the generated document, not a Markdown file, is where a client reads why a
    // 403 and a 404 mean different things here.
    expect(decide.responses["403"]?.description).toContain("BR-005");
    expect(decide.responses["404"]?.description).toContain("indistinguishable");
    expect(decide.responses["409"]?.description).toContain("concurrent");
  });

  it("marks every purchase request operation as requiring the bearer scheme", () => {
    expect(document.components.securitySchemes.accessToken?.type).toBe("http");

    for (const [path, methods] of Object.entries(document.paths)) {
      if (!path.startsWith("/purchase-requests")) {
        continue;
      }

      for (const operationObject of Object.values(methods)) {
        expect(operationObject.security).toEqual([{ accessToken: [] }]);
      }
    }
  });
});
